apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment  #deployment name 
spec:
  replicas: 2 #number of pods 
  selector:
    matchLabels: 
      app: ping
  template: #template of pods 
    metadata:
      labels: # each app gets the same label
        app: ping
    spec:
      containers: #name of the container 
      - name: ping-pod #pod name 
        image: test_deploy_ml:latest #docker image 
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
        ports:
        - containerPort: 9696
